✨ more policy and opa utils (#102)
- Adds a registry service for offline mode
- Adds policy and opa CLI tools to pre-reqs, but you have to request them (they aren't default)
- Updates to renamed `entitlement_store` image

diff --git a/examples/offline/build-offline-bundle b/examples/offline/build-offline-bundle
--- a/examples/offline/build-offline-bundle
+++ b/examples/offline/build-offline-bundle
@@ -137,7 +137,7 @@ export save-image
 
 # TODO(PLAT-1417) add 'storage' once published to ghcr.io
 if [[ ! $no_first_party ]]; then
-  for x in attributes entitlement-store entitlement-pdp entitlements kas keycloak keycloak-bootstrap; do
+  for x in attributes entitlement_store entitlement-pdp entitlements kas keycloak keycloak-bootstrap; do
     save-image "ghcr.io/opentdf/${x}" "${BACKEND_IMAGE_TAG}" "opentdf-${x}"
   done
   # shellcheck disable=SC2043 # Keep this similar to the backend loop
@@ -177,6 +177,10 @@ if ! helm pull --repo https://codecentric.github.io/helm-charts --version 17.0.1
 fi
 if ! helm pull --repo https://charts.bitnami.com/bitnami --version 10.16.2 --destination "${OUT_DIR}/charts" postgresql; then
   monolog ERROR "Unable to helm pull postgresql"
+  exit 1
+fi
+if ! helm pull --repo https://helm.twun.io --version 2.1.0 --destination "${OUT_DIR}/charts" docker-registry; then
+  monolog ERROR "Unable to helm pull twuni/docker-registry"
   exit 1
 fi
 
